/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Endereco;
import modelos.ICrud;
import modelos.Oficina;
import modelos.Telefone;
import persistencia.OficinaDAO;

/**
 *
 * @author Cliente
 */
public class TelaOficinas extends javax.swing.JInternalFrame {
  private ICrud<Oficina> OficinaBD = null;
    /**
     * Creates new form TelaOficinas
     */
    public TelaOficinas() {
        initComponents();
    try {
      OficinaBD = new OficinaDAO();
      mostrarOficinaNaGrid();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
    }
    }
  private void limparTela(){
    jTextField1_nome.setText("");
    jTextField3_email.setText("");
    jTextField1_logradouro.setText("");
    jTextField2_numero.setText("");
    jTextField3_BAIRO.setText("");
    jFormattedTextField1_cep.setValue(null);
    jTextField3_complemento.setText("");
    jTextField5_cidade.setText("");
    jTextField6_estado.setText("");
    jFormattedTextField1_telefone.setValue(null);
    jFormattedTextField1_telefone2.setValue(null);
  }
  private void mostrarOficinaNaGrid(){
  try {
    List<Oficina> listaDeOficina = new ArrayList<>();
    listaDeOficina = null;
    listaDeOficina = OficinaBD.listar();
    if(listaDeOficina != null){
    DefaultTableModel model =  (DefaultTableModel) jTableOficina.getModel();
    model.setNumRows(0); 
    if(listaDeOficina.isEmpty()) 
      throw new Exception("Lista de Oficina BD Vazia");
    
        jTableOficina.setRowHeight(75);
    for(int j = 0; j<5;j++){
        jTableOficina.getColumnModel().getColumn(j).setCellRenderer(new MultiLineTableCellRenderer());
         }
    for(int pos = 0; pos < listaDeOficina.size(); pos++){
      Oficina objOficina = listaDeOficina.get(pos);
      String[] saida = new String[5];
        saida[0] = objOficina.getIdentificador_Email()+ "";
        saida[1] = objOficina.getNome() + "";
        saida[2] = objOficina.getTelefone1().toString()+ "";
        if(objOficina.getTelefone2()!=null){
            saida[3] = objOficina.getTelefone2().toString()+ "";
        }else{
            saida[3] = "";
        }
        saida[4] = objOficina.getEndereco().toString()+ "";
      model.addRow(saida);
    }  
    }
  } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1_telefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_nome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField1_telefone2 = new javax.swing.JFormattedTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField2_numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField1_cep = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField3_BAIRO = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6_estado = new javax.swing.JTextField();
        jTextField5_cidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3_complemento = new javax.swing.JTextField();
        jTextField1_logradouro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOficina = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(957, 466));
        setPreferredSize(new java.awt.Dimension(957, 466));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE OFICINA");

        jTextField3_email.setBackground(new java.awt.Color(204, 255, 204));
        jTextField3_email.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setText("Email");

        jFormattedTextField1_telefone.setBackground(new java.awt.Color(204, 255, 204));
        try {
            jFormattedTextField1_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_telefone.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setText("Telefone1");

        jTextField1_nome.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1_nome.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextField1_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_nomeActionPerformed(evt);
            }
        });
        jTextField1_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_nomeKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel16.setText("Telefone2");

        jFormattedTextField1_telefone2.setBackground(new java.awt.Color(204, 255, 204));
        try {
            jFormattedTextField1_telefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_telefone2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        jButtonIncluir.setBackground(new java.awt.Color(0, 153, 0));
        jButtonIncluir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonIncluir.setForeground(new java.awt.Color(0, 255, 204));
        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/seta.png"))); // NOI18N
        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAlterar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(0, 255, 204));
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/troca.png"))); // NOI18N
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButton_buscar.setBackground(new java.awt.Color(0, 153, 0));
        jButton_buscar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(0, 255, 204));
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/procurar.png"))); // NOI18N
        jButton_buscar.setText("BUSCAR");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("LOGADOURO");

        jTextField2_numero.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_numeroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("NUMERO");

        jFormattedTextField1_cep.setBackground(new java.awt.Color(204, 255, 204));
        try {
            jFormattedTextField1_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("BAIRRO");

        jTextField3_BAIRO.setBackground(new java.awt.Color(204, 255, 204));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("ESTADO");

        jTextField6_estado.setBackground(new java.awt.Color(204, 255, 204));

        jTextField5_cidade.setBackground(new java.awt.Color(204, 255, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("CIDADE");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("CEP");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("COMPLEMENTO");

        jTextField3_complemento.setBackground(new java.awt.Color(204, 255, 204));

        jTextField1_logradouro.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1_logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_logradouroActionPerformed(evt);
            }
        });

        jTableOficina.setBackground(new java.awt.Color(153, 255, 204));
        jTableOficina.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jTableOficina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDENTIFICADOR_EMAIL", "NOME", "TELEFONE1", "TELEFONE2", "ENDERECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOficinaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOficina);
        if (jTableOficina.getColumnModel().getColumnCount() > 0) {
            jTableOficina.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableOficina.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableOficina.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3_email, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField1_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField1_telefone2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField2_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jFormattedTextField1_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3_BAIRO, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextField3_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonIncluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addGap(18, 18, 18)
                .addComponent(jButton_buscar)
                .addGap(449, 449, 449))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextField1_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextField1_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jTextField3_BAIRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextField1_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jFormattedTextField1_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField3_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel14))
                        .addComponent(jLabel12)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButton_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_logradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_logradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_logradouroActionPerformed

    private void jTextField1_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_nomeActionPerformed

    }//GEN-LAST:event_jTextField1_nomeActionPerformed

    private void jTextField1_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_nomeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nomeKeyReleased

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try {
            
            if(jTextField3_email.getText().isEmpty()) throw new Exception("email vazio");
            String email = jTextField3_email.getText();
            Oficina objeto = new Oficina(email);
            objeto = OficinaBD.consultar(objeto);
            

            jTextField1_nome.setText(objeto.getNome());
            jTextField3_email.setText(objeto.getIdentificador_Email());
            jFormattedTextField1_cep.setText(objeto.getEndereco().getCep());
            jTextField1_logradouro.setText(objeto.getEndereco().getLogradouro());
            jTextField2_numero.setText(objeto.getEndereco().getNumeroEndereco()+"");
            jTextField3_BAIRO.setText(objeto.getEndereco().getBairro());
            jTextField3_complemento.setText(objeto.getEndereco().getComplemento());
            jTextField5_cidade.setText(objeto.getEndereco().getCidade());
            jTextField6_estado.setText(objeto.getEndereco().getEstado()+"");
            String valueTelefone1 = ""+objeto.getTelefone1().getDdi()+objeto.getTelefone1().getDdd()+objeto.getTelefone1().getNumero();
            jFormattedTextField1_telefone.setText(valueTelefone1);
            if(objeto.getTelefone2()!=null){
                String valueTelefone2 = ""+objeto.getTelefone2().getDdi()+objeto.getTelefone2().getDdd()+objeto.getTelefone2().getNumero();
                jFormattedTextField1_telefone2.setText(valueTelefone2);
            }else{
                jFormattedTextField1_telefone2.setValue(null);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            // Validação do nome da oficina
            String nome = jTextField1_nome.getText().trim().toUpperCase();
            if (nome.isEmpty()) {
                throw new Exception("O campo de nome não pode estar vazio.");
            }

            // Validação do email
            String email = jTextField3_email.getText().trim();
            if (email.isEmpty()) {
                throw new Exception("O campo de email não pode estar vazio.");
            }
            if (!email.matches("^[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}$")) {
                throw new Exception("Insira um email válido no formato: exemplo@dominio.com.");
            }

            // Validação do telefone principal
            String numeroTele = jFormattedTextField1_telefone.getText().trim();
            if (numeroTele.isEmpty()) {
                throw new Exception("O telefone principal não pode estar vazio.");
            }
            if (!numeroTele.matches("\\+\\d{2}\\(\\d{2}\\)\\d{8,9}")) {
                throw new Exception("Insira um telefone principal válido no formato: +XX(XX)XXXXXXXXX.");
            }

            // Extrai partes do telefone principal
            String[] telefonePartes = numeroTele.split("[() -]+");
            int ddi = Integer.parseInt(telefonePartes[0]);
            int ddd = Integer.parseInt(telefonePartes[1]);
            int numero = Integer.parseInt(telefonePartes[2]);

            // Validação do telefone secundário (opcional)
            Telefone telefone2 = null;
            String numeroTele2 = jFormattedTextField1_telefone2.getText();
            if(!numeroTele2.equals("+  (  )         ")){
                String[] telefonePartes2 = numeroTele2.split("[()]+");
                int ddi2 = Integer.parseInt(telefonePartes2[0].substring(1));
                int ddd2 = Integer.parseInt(telefonePartes2[1]);
                int numero2 = Integer.parseInt(telefonePartes2[2]);
                telefone2 = new Telefone(ddi2,ddd2,numero2);
            }

            // Validação do endereço
            String logradouro = jTextField1_logradouro.getText().trim().toUpperCase();
            if (logradouro.isEmpty()) {
                throw new Exception("O campo de logradouro não pode estar vazio.");
            }

            String numeroEndereco = jTextField2_numero.getText().trim();
            if (numeroEndereco.isEmpty() || !numeroEndereco.matches("\\d+")) {
                throw new Exception("O número do endereço deve ser um número válido.");
            }

            String cep = jFormattedTextField1_cep.getText().trim();
            if (cep.isEmpty() || !cep.matches("\\d{5}\\-\\d{3}")) {
                throw new Exception("Insira um CEP válido no formato: XXXXX-XXX.");
            }

            String bairro = jTextField3_BAIRO.getText().trim().toUpperCase();
            if (bairro.isEmpty()) {
                throw new Exception("O campo de bairro não pode estar vazio.");
            }

            String complemento = jTextField3_complemento.getText().trim().toUpperCase();

            String cidade = jTextField5_cidade.getText().trim().toUpperCase();
            if (cidade.isEmpty()) {
                throw new Exception("O campo de cidade não pode estar vazio.");
            }

            String estado = jTextField6_estado.getText().trim().toUpperCase();
            if (estado.isEmpty() || estado.length() != 2 || !estado.matches("[A-Z]{2}")) {
                throw new Exception("O campo de estado deve conter 2 letras (ex: SP, RJ).");
            }

            // Criação dos objetos
            Telefone telefone1 = new Telefone(ddi, ddd, numero);
            Endereco endereco = new Endereco(logradouro, Integer.parseInt(numeroEndereco), cep, bairro, complemento, cidade, estado);
            Oficina objOficina = new Oficina(email, nome, telefone1, telefone2, endereco);

            // Inserção no banco de dados
            OficinaBD.incluir(objOficina);

            // Limpa a tela e atualiza a tabela
            limparTela();
            mostrarOficinaNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visão: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {
            // Validação do nome da oficina
            String nome = jTextField1_nome.getText().trim().toUpperCase();
            if (nome.isEmpty()) {
                throw new Exception("O campo de nome não pode estar vazio.");
            }

            // Validação do email
            String email = jTextField3_email.getText().trim();
            if (email.isEmpty()) {
                throw new Exception("O campo de email não pode estar vazio.");
            }
            if (!email.matches("^[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}$")) {
                throw new Exception("Insira um email válido no formato: exemplo@dominio.com.");
            }

            // Validação do telefone principal
            String numeroTele = jFormattedTextField1_telefone.getText().trim();
            if (numeroTele.isEmpty()) {
                throw new Exception("O telefone principal não pode estar vazio.");
            }
            if (!numeroTele.matches("\\+\\d{2}\\(\\d{2}\\)\\d{8,9}")) {
                throw new Exception("Insira um telefone principal válido no formato: +XX(XX)XXXXXXXXX.");
            }

            // Extrai partes do telefone principal
            String[] telefonePartes = numeroTele.split("[() -]+");
            int ddi = Integer.parseInt(telefonePartes[0]);
            int ddd = Integer.parseInt(telefonePartes[1]);
            int numero = Integer.parseInt(telefonePartes[2]);

            // Validação do telefone secundário (opcional)
            Telefone telefone2 = null;
            String numeroTele2 = jFormattedTextField1_telefone2.getText();
            if(!numeroTele2.equals("+  (  )         ")){
                String[] telefonePartes2 = numeroTele2.split("[()]+");
                int ddi2 = Integer.parseInt(telefonePartes2[0].substring(1));
                int ddd2 = Integer.parseInt(telefonePartes2[1]);
                int numero2 = Integer.parseInt(telefonePartes2[2]);
                telefone2 = new Telefone(ddi2,ddd2,numero2);
            }

            // Validação do endereço
            String logradouro = jTextField1_logradouro.getText().trim().toUpperCase();
            if (logradouro.isEmpty()) {
                throw new Exception("O campo de logradouro não pode estar vazio.");
            }

            String numeroEndereco = jTextField2_numero.getText().trim();
            if (numeroEndereco.isEmpty() || !numeroEndereco.matches("\\d+")) {
                throw new Exception("O número do endereço deve ser um número válido.");
            }

            String cep = jFormattedTextField1_cep.getText().trim();
            if (cep.isEmpty() || !cep.matches("\\d{5}\\-\\d{3}")) {
                throw new Exception("Insira um CEP válido no formato: XXXXX-XXX.");
            }

            String bairro = jTextField3_BAIRO.getText().trim().toUpperCase();
            if (bairro.isEmpty()) {
                throw new Exception("O campo de bairro não pode estar vazio.");
            }

            String complemento = jTextField3_complemento.getText().trim().toUpperCase();

            String cidade = jTextField5_cidade.getText().trim().toUpperCase();
            if (cidade.isEmpty()) {
                throw new Exception("O campo de cidade não pode estar vazio.");
            }

            String estado = jTextField6_estado.getText().trim().toUpperCase();
            if (estado.isEmpty() || estado.length() != 2 || !estado.matches("[A-Z]{2}")) {
                throw new Exception("O campo de estado deve conter 2 letras (ex: SP, RJ).");
            }

            // Criação dos objetos
            Telefone telefone1 = new Telefone(ddi, ddd, numero);
            Endereco endereco = new Endereco(logradouro, Integer.parseInt(numeroEndereco), cep, bairro, complemento, cidade, estado);
            Oficina objOficina = new Oficina(email, nome, telefone1, telefone2, endereco);
            OficinaBD.alterar(objOficina);
            limparTela();
            mostrarOficinaNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextField2_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_numeroActionPerformed

    private void jTableOficinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOficinaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTableOficina.getModel();
        int selectedRowIndex = jTableOficina.getSelectedRow();
        
        jTextField3_email.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField1_nome.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jFormattedTextField1_telefone.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jFormattedTextField1_telefone2.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
        String auxEnd = model.getValueAt(selectedRowIndex, 4).toString();
        String vetEnd[] = auxEnd.split("[\u200B,-]");
        jTextField1_logradouro.setText(vetEnd[0].trim());
        jTextField2_numero.setText(vetEnd[1].trim());
        jTextField3_complemento.setText(vetEnd[2].trim());
        jTextField3_BAIRO.setText(vetEnd[3].trim());
        jTextField5_cidade.setText(vetEnd[4].trim());
        jTextField6_estado.setText(vetEnd[5].trim());
        jFormattedTextField1_cep.setText((vetEnd[6]+"-"+vetEnd[7]).trim());
        
        //aux
        //String vetTelefone1[] = model.getValueAt
    }//GEN-LAST:event_jTableOficinaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JFormattedTextField jFormattedTextField1_cep;
    private javax.swing.JFormattedTextField jFormattedTextField1_telefone;
    private javax.swing.JFormattedTextField jFormattedTextField1_telefone2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOficina;
    private javax.swing.JTextField jTextField1_logradouro;
    private javax.swing.JTextField jTextField1_nome;
    private javax.swing.JTextField jTextField2_numero;
    private javax.swing.JTextField jTextField3_BAIRO;
    private javax.swing.JTextField jTextField3_complemento;
    private javax.swing.JTextField jTextField3_email;
    private javax.swing.JTextField jTextField5_cidade;
    private javax.swing.JTextField jTextField6_estado;
    // End of variables declaration//GEN-END:variables
}
