/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Acessorio;
import modelos.Cliente;
import modelos.OrdemDeServico;
import modelos.ICrud;
import modelos.ItensPeca;
import modelos.ItensServicos;
import modelos.Oficina;
import modelos.Proprietario;
import modelos.Veiculo;
import modelos.VeiculoAcessorio;
import modelos.enums.StatusEnum;
import pdf.GerarPDF;
import persistencia.ClienteDAO;
import persistencia.ItensPecaDAO;
import persistencia.ItensServicosDAO;
import persistencia.OficinaDAO;
import persistencia.OrdemDeServicoDAO;
import persistencia.ProprietarioDAO;
import persistencia.VeiculoAcessorioDAO;
import persistencia.VeiculoDAO;

/**
 *
 * @author misuka
 */
public class TelaOrdemDeServico extends javax.swing.JInternalFrame {

    private Date dataAtual = null;
    private ICrud<Veiculo> veiculoDB = null;
    private ICrud<Oficina> oficinaBD = null;
    private ICrud<VeiculoAcessorio> veiculoAcessorioBD = null;
    private ICrud<ItensServicos> itensServicoBD = null;
    private ICrud<ItensPeca> itensPecaBD = null;
    private ICrud<Proprietario> proprietarioBD = null;
    private ICrud<Cliente> clienteBD = null;
    private ICrud<OrdemDeServico> ordemDB = null;
    
    public TelaOrdemDeServico() {
        initComponents();
        try {
            dataAtual = jCalendar_DataInicio.getDate();
            veiculoDB = new VeiculoDAO();
            ordemDB = new OrdemDeServicoDAO();
            oficinaBD = new OficinaDAO();
          
            List<Veiculo> listaDeVeiculo = veiculoDB.listar();
            jComboBox_Veiculo.removeAllItems();
            for(int pos = 0; pos < listaDeVeiculo.size(); pos++){
                jComboBox_Veiculo.addItem(listaDeVeiculo.get(pos).toString());
            }
            
            jComboBox_Status.removeAll();
            for(StatusEnum status : StatusEnum.values()){
                jComboBox_Status.addItem(status.getDescricao());
            }
            
            List<Oficina> listaDeOficina = oficinaBD.listar();
            jComboBox_Oficina.removeAllItems();
            for(int pos = 0; pos < listaDeOficina.size(); pos++){
                jComboBox_Oficina.addItem(listaDeOficina.get(pos).toString());
            }
            jTextField_Diferenca.setEditable(false);
            mostrarNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
        }
    }
    
    private void limparTela(){
        jCalendar_DataInicio.setDate(dataAtual);
        jCalendar_DataFim.setDate(dataAtual);
        jComboBox_Veiculo.setSelectedIndex(0);
        jComboBox_Status.setSelectedIndex(0);
        jTextField_ValorTotal.setText("");
        jTextField_ID.setText("");
        jTextField_ValorPago.setText("");
        jTextField_Diferenca.setText("");
    }
    
    private void mostrarNaGrid(){
        try {
            List<OrdemDeServico> listaDeOrdem = null;
            listaDeOrdem = ordemDB.listar();
            DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
            model.setNumRows(0); 
            if(listaDeOrdem.isEmpty()) throw new Exception("Lista de Oficina BD Vazia");

            jTable_Saida.setRowHeight(75);
            for(int j = 0; j<8;j++){
                jTable_Saida.getColumnModel().getColumn(j).setCellRenderer(new MultiLineTableCellRenderer());
            }
            for(int pos = 0; pos < listaDeOrdem.size(); pos++){
                OrdemDeServico objOrdem = listaDeOrdem.get(pos);
                String[] saida = new String[8];
                saida[0] = objOrdem.getIdOrdem()+"";
                saida[1] = objOrdem.getStatus();
                saida[2] = objOrdem.getDataInicio()+"";
                saida[3] = objOrdem.getDataFim()+"";
                saida[4] = objOrdem.getValorTotal();
                saida[5] = objOrdem.getValorPago();
                saida[6] = objOrdem.getDiferenca();
                saida[7] = objOrdem.getVeiculo().toString();
                model.addRow(saida);
            }  
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ValorTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_ValorPago = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Diferenca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Veiculo = new javax.swing.JComboBox<>();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jCalendar_DataInicio = new com.toedter.calendar.JCalendar();
        jLabel8 = new javax.swing.JLabel();
        jCalendar_DataFim = new com.toedter.calendar.JCalendar();
        jButton1_pdf = new javax.swing.JButton();
        jComboBox_Oficina = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("ID");

        jTextField_ID.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Status");

        jComboBox_Status.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Valor Total");

        jTextField_ValorTotal.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Valor Pago");

        jTextField_ValorPago.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Diferença");

        jTextField_Diferenca.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Veículo");

        jComboBox_Veiculo.setBackground(new java.awt.Color(204, 255, 204));

        jButton_Incluir.setBackground(new java.awt.Color(0, 153, 0));
        jButton_Incluir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton_Incluir.setForeground(new java.awt.Color(0, 255, 204));
        jButton_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/seta.png"))); // NOI18N
        jButton_Incluir.setText("INCLUIR");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Alterar.setBackground(new java.awt.Color(0, 153, 0));
        jButton_Alterar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton_Alterar.setForeground(new java.awt.Color(0, 255, 204));
        jButton_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/troca.png"))); // NOI18N
        jButton_Alterar.setText("ALTERAR");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Buscar.setBackground(new java.awt.Color(0, 153, 0));
        jButton_Buscar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton_Buscar.setForeground(new java.awt.Color(0, 255, 204));
        jButton_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/procurar.png"))); // NOI18N
        jButton_Buscar.setText("BUSCAR");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jTable_Saida.setBackground(new java.awt.Color(153, 255, 204));
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status", "Data Inicio", "Data Fim", "Valor Total", "Valor Pago", "Diferença", "Veiculo"
            }
        ));
        jTable_Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Saida);
        if (jTable_Saida.getColumnModel().getColumnCount() > 0) {
            jTable_Saida.getColumnModel().getColumn(0).setMinWidth(50);
            jTable_Saida.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_Saida.getColumnModel().getColumn(1).setMinWidth(120);
            jTable_Saida.getColumnModel().getColumn(1).setMaxWidth(120);
            jTable_Saida.getColumnModel().getColumn(2).setMinWidth(120);
            jTable_Saida.getColumnModel().getColumn(2).setMaxWidth(120);
            jTable_Saida.getColumnModel().getColumn(3).setMinWidth(120);
            jTable_Saida.getColumnModel().getColumn(3).setMaxWidth(120);
            jTable_Saida.getColumnModel().getColumn(4).setMinWidth(90);
            jTable_Saida.getColumnModel().getColumn(4).setMaxWidth(90);
            jTable_Saida.getColumnModel().getColumn(5).setMinWidth(90);
            jTable_Saida.getColumnModel().getColumn(5).setMaxWidth(90);
            jTable_Saida.getColumnModel().getColumn(6).setMinWidth(90);
            jTable_Saida.getColumnModel().getColumn(6).setMaxWidth(90);
        }

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setText("Data Inicial");

        jCalendar_DataInicio.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setText("Data Final");

        jCalendar_DataFim.setBackground(new java.awt.Color(153, 255, 153));

        jButton1_pdf.setBackground(new java.awt.Color(0, 153, 0));
        jButton1_pdf.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/pdf.png"))); // NOI18N
        jButton1_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_pdfActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setText("Oficina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ValorPago))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ValorTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ID))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Diferenca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Veiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar_DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jCalendar_DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Oficina, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_ValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField_Diferenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_Incluir)
                                    .addComponent(jButton_Alterar)
                                    .addComponent(jButton_Buscar)))
                            .addComponent(jCalendar_DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCalendar_DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        try {
            OrdemDeServico objeto = new OrdemDeServico();
            objeto.setIdOrdem(0);
            
            if(jCalendar_DataInicio.getDate().after(jCalendar_DataFim.getDate())) throw new Exception("A data inicial não pode ser maior que a final");
            objeto.setDataInicio(jCalendar_DataInicio.getDate());
            objeto.setDataFim(jCalendar_DataFim.getDate());
            
            objeto.setVeiculo(new Veiculo(jComboBox_Veiculo.getSelectedItem().toString().split("-")[0]));
            
            if(!jTextField_ValorTotal.getText().replace(",", ".").matches("\\d+(\\.\\d{1,2})?")) throw new Exception("O Valor Total deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45)");
            objeto.setValorTotal(jTextField_ValorTotal.getText().replace(",", "."));
            float valorTotal = Float.parseFloat(jTextField_ValorTotal.getText().replace(",", "."));
            if(!jTextField_ValorPago.getText().replace(",", ".").matches("\\d+(\\.\\d{1,2})?")) throw new Exception("O Valor Pago deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45)");
            objeto.setValorPago(jTextField_ValorPago.getText().replace(",", "."));
            float valorPago = Float.parseFloat(jTextField_ValorPago.getText().replace(",", "."));
            float diferenca = valorTotal - valorPago;
            if(diferenca < 0.0) throw new Exception("O Valor Pago não pode ser maior que o valor total");
            objeto.setDiferenca(diferenca+"");
            
            objeto.setStatus(jComboBox_Status.getSelectedItem().toString());
            
            ordemDB.incluir(objeto);
            limparTela();
            mostrarNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao incluir Ordem de Serviço: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        // TODO add your handling code here:
        try {
            OrdemDeServico objeto = new OrdemDeServico();
            if(jTextField_ID.getText().isEmpty()) throw new Exception("ID vazio");
            objeto.setIdOrdem(Integer.parseInt(jTextField_ID.getText()));
            if(jCalendar_DataInicio.getDate().after(jCalendar_DataFim.getDate())) throw new Exception("A data inicial não pode ser maior que a final");
            objeto.setDataInicio(jCalendar_DataInicio.getDate());
            objeto.setDataFim(jCalendar_DataFim.getDate());
            
            objeto.setVeiculo(new Veiculo(jComboBox_Veiculo.getSelectedItem().toString().split("-")[0]));
            
            if(!jTextField_ValorTotal.getText().replace(",", ".").matches("\\d+(\\.\\d{1,2})?")) throw new Exception("O Valor Total deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45)");
            objeto.setValorTotal(jTextField_ValorTotal.getText().replace(",", "."));
            float valorTotal = Float.parseFloat(jTextField_ValorTotal.getText().replace(",", "."));
            if(!jTextField_ValorPago.getText().replace(",", ".").matches("\\d+(\\.\\d{1,2})?")) throw new Exception("O Valor Pago deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45)");
            objeto.setValorPago(jTextField_ValorPago.getText().replace(",", "."));
            float valorPago = Float.parseFloat(jTextField_ValorPago.getText().replace(",", "."));
            float diferenca = valorTotal - valorPago;
            if(diferenca < 0.0) throw new Exception("O Valor Pago não pode ser maior que o valor total");
            objeto.setDiferenca(diferenca+"");
            
            objeto.setStatus(jComboBox_Status.getSelectedItem().toString());
            ordemDB.alterar(objeto);
            limparTela();
            mostrarNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao alterar Ordem de Serviço: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            OrdemDeServico objeto = ordemDB.consultar(new OrdemDeServico(Integer.parseInt(jTextField_ID.getText())));

            jTextField_ID.setText(objeto.getIdOrdem()+"");

            jCalendar_DataInicio.setDate(objeto.getDataInicio());
            jCalendar_DataFim.setDate(objeto.getDataFim());

            jComboBox_Veiculo.setSelectedItem(objeto.getVeiculo().toString());
            jComboBox_Status.setSelectedItem(objeto.getStatus());
            
            jTextField_ValorTotal.setText(objeto.getValorTotal().replace("R$", "").trim());
            jTextField_ValorPago.setText(objeto.getValorPago().replace("R$", "").trim());
            jTextField_Diferenca.setText(objeto.getDiferenca().replace("R$", "").trim());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar proprietário: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTable_SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SaidaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable_Saida.getModel();
        int selectedRowIndex = jTable_Saida.getSelectedRow();
        
        jTextField_ID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jComboBox_Status.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
        
        String strDataInicio = (String) model.getValueAt(selectedRowIndex, 2);
        String[] vetDataInicio = strDataInicio.split("-");
        Calendar dataInicio = Calendar.getInstance();
        dataInicio.set(Calendar.YEAR, Integer.parseInt(vetDataInicio[0]));
        dataInicio.set(Calendar.MONTH, Integer.parseInt(vetDataInicio[1]) - 1);
        dataInicio.set(Calendar.DAY_OF_MONTH, Integer.parseInt(vetDataInicio[2]));
        jCalendar_DataInicio.setDate(dataInicio.getTime());
        
        String strDataFim = (String) model.getValueAt(selectedRowIndex, 3);
        String[] vetDataFim = strDataFim.split("-");
        Calendar dataFim = Calendar.getInstance();
        dataFim.set(Calendar.YEAR, Integer.parseInt(vetDataFim[0]));
        dataFim.set(Calendar.MONTH, Integer.parseInt(vetDataFim[1]) - 1);
        dataFim.set(Calendar.DAY_OF_MONTH, Integer.parseInt(vetDataFim[2]));
        jCalendar_DataFim.setDate(dataFim.getTime());
        
        jTextField_ValorTotal.setText(model.getValueAt(selectedRowIndex, 4).toString().replace("R$", "").trim());
        jTextField_ValorPago.setText(model.getValueAt(selectedRowIndex, 5).toString().replace("R$", "").trim());
        jTextField_Diferenca.setText(model.getValueAt(selectedRowIndex, 6).toString().replace("R$", "").trim());
        jComboBox_Veiculo.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());

    }//GEN-LAST:event_jTable_SaidaMouseClicked

    private void jButton1_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_pdfActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextField_ID.getText().isEmpty()) throw new Exception("ID Vazio");
            GerarPDF pdf = new GerarPDF();
            Cliente cliente = null;
            proprietarioBD = new ProprietarioDAO();
            clienteBD = new ClienteDAO();
            List<Proprietario> listaDeProprietario = null;
            listaDeProprietario = proprietarioBD.listar();
            for(int pos = 0; pos < listaDeProprietario.size(); pos++){
                Proprietario objProprietario = listaDeProprietario.get(pos);
                if(objProprietario.getDataFim()== null && objProprietario.getVeiculo().getPlaca().compareTo(jComboBox_Veiculo.getSelectedItem().toString().split("-")[0])==0){
                    cliente = clienteBD.consultar(new Cliente(objProprietario.getCliente().getIdCliente()));
                }
            }         
            List<Acessorio> listaDeAcessorio = null;
            listaDeAcessorio = new LinkedList<>();
            veiculoAcessorioBD = new VeiculoAcessorioDAO();
            List<VeiculoAcessorio> listaDeVeiculoAcessorio = null;
            listaDeVeiculoAcessorio = veiculoAcessorioBD.listar();
            for(int pos = 0; pos < listaDeVeiculoAcessorio.size(); pos++){
                VeiculoAcessorio objVeiculoAcessorio = listaDeVeiculoAcessorio.get(pos);
                if(objVeiculoAcessorio.getVeiculo().getPlaca().compareTo(jComboBox_Veiculo.getSelectedItem().toString().split("-")[0])==0){
                    listaDeAcessorio.add(objVeiculoAcessorio.getAcessorio());
                }
            }
            List<ItensPeca> listaDePecasOrdemAtual = null;
            listaDePecasOrdemAtual = new LinkedList<>();
            itensPecaBD = new ItensPecaDAO();
            List<ItensPeca> listaDeBuscaOrdemPecas = null;
            listaDeBuscaOrdemPecas = itensPecaBD.listar();
            for(int pos = 0; pos < listaDeBuscaOrdemPecas.size(); pos++){
                ItensPeca objItensPecas = listaDeBuscaOrdemPecas.get(pos);
                if(objItensPecas.getOrdem().getIdOrdem() == Integer.parseInt(jTextField_ID.getText())){
                    listaDePecasOrdemAtual.add(objItensPecas);
                }
            }
            List<ItensServicos> listaDeServicoOrdemAtual = null;
            listaDeServicoOrdemAtual = new LinkedList<>();
            itensServicoBD = new ItensServicosDAO();
            List<ItensServicos> listaDeBuscaOrdemServico = null;
            listaDeBuscaOrdemServico = itensServicoBD.listar();
            for(int pos = 0; pos < listaDeBuscaOrdemServico.size(); pos++){
                ItensServicos objItensServico = listaDeBuscaOrdemServico.get(pos);
                if(objItensServico.getOrdem().getIdOrdem() == Integer.parseInt(jTextField_ID.getText())){
                    listaDeServicoOrdemAtual.add(objItensServico);
                }
            }
            
            Oficina oficina = (oficinaBD.consultar(new Oficina(jComboBox_Oficina.getSelectedItem().toString().split("-")[0])));
            Veiculo veiculo = (veiculoDB.consultar(new Veiculo(jComboBox_Veiculo.getSelectedItem().toString().split("-")[0])));
            OrdemDeServico ordem = new OrdemDeServico(Integer.parseInt(jTextField_ID.getText()));
            pdf.gerarPdf(ordem,veiculo,cliente,listaDeAcessorio,listaDePecasOrdemAtual,listaDeServicoOrdemAtual,oficina);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Gerar PDF: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton1_pdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_pdf;
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Incluir;
    private com.toedter.calendar.JCalendar jCalendar_DataFim;
    private com.toedter.calendar.JCalendar jCalendar_DataInicio;
    private javax.swing.JComboBox<String> jComboBox_Oficina;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JComboBox<String> jComboBox_Veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    private javax.swing.JTextField jTextField_Diferenca;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_ValorPago;
    private javax.swing.JTextField jTextField_ValorTotal;
    // End of variables declaration//GEN-END:variables
}
