/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ejmcc
 */
public class TelaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form TelaPrincipal
   */
    
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jMenu_Oficina.setPopupMenuVisible(false);
        WindowClosingEventHandler();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        // Como inserir uma tela na tela principal
        jDesktopPane_InputDeTela.removeAll();
        TelaBemVindo_JInternalFrame telaBemVindo = new TelaBemVindo_JInternalFrame();
        jDesktopPane_InputDeTela.add(telaBemVindo);
        try {
            telaBemVindo.setVisible(true);
            telaBemVindo.setSelected(true);
            telaBemVindo.setMaximum(true);
            telaBemVindo.setMaximizable(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    private void WindowClosingEventHandler(){
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int resposta = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja fechar?","Confirmação", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION){
                    dispose();
                }
            }
        });
    }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane_InputDeTela = new javax.swing.JDesktopPane();
        jMenuBar_Opcoes = new javax.swing.JMenuBar();
        jMenu_Oficina = new javax.swing.JMenu();
        jMenu_ClientesVeiculos = new javax.swing.JMenu();
        jMenuItem_Cliente = new javax.swing.JMenuItem();
        jMenu_OpcoesVeiculo = new javax.swing.JMenu();
        jMenuItem_Marca = new javax.swing.JMenuItem();
        jMenuItem_Modelo = new javax.swing.JMenuItem();
        jMenuItem_Acessorio = new javax.swing.JMenuItem();
        jMenuItem_Veiculo = new javax.swing.JMenuItem();
        jMenuItem_VeiculoAcessorio = new javax.swing.JMenuItem();
        jMenuItem_Proprietario = new javax.swing.JMenuItem();
        jMenu_PecasServicos = new javax.swing.JMenu();
        jMenu_OpcoesPeca = new javax.swing.JMenu();
        jMenuItem_Peca = new javax.swing.JMenuItem();
        jMenuItem_ItensDePeca = new javax.swing.JMenuItem();
        jMenu_OpcoesServico = new javax.swing.JMenu();
        jMenuItem_Funcionario = new javax.swing.JMenuItem();
        jMenuItem_Servico = new javax.swing.JMenuItem();
        jMenuItem_ItensDeServico = new javax.swing.JMenuItem();
        jMenuItem_OrdemDeServico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane_InputDeTela.setPreferredSize(new java.awt.Dimension(957, 466));

        javax.swing.GroupLayout jDesktopPane_InputDeTelaLayout = new javax.swing.GroupLayout(jDesktopPane_InputDeTela);
        jDesktopPane_InputDeTela.setLayout(jDesktopPane_InputDeTelaLayout);
        jDesktopPane_InputDeTelaLayout.setHorizontalGroup(
            jDesktopPane_InputDeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        jDesktopPane_InputDeTelaLayout.setVerticalGroup(
            jDesktopPane_InputDeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jMenu_Oficina.setText("Oficina");
        jMenu_Oficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_OficinaMousePressed(evt);
            }
        });
        jMenuBar_Opcoes.add(jMenu_Oficina);

        jMenu_ClientesVeiculos.setText("Clientes e Veículos");

        jMenuItem_Cliente.setText("Cliente");
        jMenuItem_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ClienteActionPerformed(evt);
            }
        });
        jMenu_ClientesVeiculos.add(jMenuItem_Cliente);

        jMenu_OpcoesVeiculo.setText("Opções Veículo");

        jMenuItem_Marca.setText("Marca");
        jMenuItem_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MarcaActionPerformed(evt);
            }
        });
        jMenu_OpcoesVeiculo.add(jMenuItem_Marca);

        jMenuItem_Modelo.setText("Modelo");
        jMenuItem_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ModeloActionPerformed(evt);
            }
        });
        jMenu_OpcoesVeiculo.add(jMenuItem_Modelo);

        jMenuItem_Acessorio.setText("Acessório");
        jMenuItem_Acessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AcessorioActionPerformed(evt);
            }
        });
        jMenu_OpcoesVeiculo.add(jMenuItem_Acessorio);

        jMenuItem_Veiculo.setText("Veículo");
        jMenuItem_Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_VeiculoActionPerformed(evt);
            }
        });
        jMenu_OpcoesVeiculo.add(jMenuItem_Veiculo);

        jMenuItem_VeiculoAcessorio.setText("Acessórios do Veículo");
        jMenuItem_VeiculoAcessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_VeiculoAcessorioActionPerformed(evt);
            }
        });
        jMenu_OpcoesVeiculo.add(jMenuItem_VeiculoAcessorio);

        jMenu_ClientesVeiculos.add(jMenu_OpcoesVeiculo);

        jMenuItem_Proprietario.setText("Proprietário");
        jMenuItem_Proprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ProprietarioActionPerformed(evt);
            }
        });
        jMenu_ClientesVeiculos.add(jMenuItem_Proprietario);

        jMenuBar_Opcoes.add(jMenu_ClientesVeiculos);

        jMenu_PecasServicos.setText("Peças e Serviços");

        jMenu_OpcoesPeca.setText("Opções de Peça");

        jMenuItem_Peca.setText("Peça");
        jMenuItem_Peca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PecaActionPerformed(evt);
            }
        });
        jMenu_OpcoesPeca.add(jMenuItem_Peca);

        jMenuItem_ItensDePeca.setText("Itens de Peça");
        jMenuItem_ItensDePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ItensDePecaActionPerformed(evt);
            }
        });
        jMenu_OpcoesPeca.add(jMenuItem_ItensDePeca);

        jMenu_PecasServicos.add(jMenu_OpcoesPeca);

        jMenu_OpcoesServico.setText("Opções de Serviço");

        jMenuItem_Funcionario.setText("Funcionário");
        jMenuItem_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FuncionarioActionPerformed(evt);
            }
        });
        jMenu_OpcoesServico.add(jMenuItem_Funcionario);

        jMenuItem_Servico.setText("Serviço");
        jMenuItem_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ServicoActionPerformed(evt);
            }
        });
        jMenu_OpcoesServico.add(jMenuItem_Servico);

        jMenuItem_ItensDeServico.setText("Itens de Serviço");
        jMenuItem_ItensDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ItensDeServicoActionPerformed(evt);
            }
        });
        jMenu_OpcoesServico.add(jMenuItem_ItensDeServico);

        jMenu_PecasServicos.add(jMenu_OpcoesServico);

        jMenuItem_OrdemDeServico.setText("Ordem de Serviço");
        jMenuItem_OrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_OrdemDeServicoActionPerformed(evt);
            }
        });
        jMenu_PecasServicos.add(jMenuItem_OrdemDeServico);

        jMenuBar_Opcoes.add(jMenu_PecasServicos);

        setJMenuBar(jMenuBar_Opcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jDesktopPane_InputDeTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane_InputDeTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_OficinaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_OficinaMousePressed
        // Abrir a parte da oficina
        
    }//GEN-LAST:event_jMenu_OficinaMousePressed

    private void jMenuItem_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ClienteActionPerformed
        // Abrir a parte do cliente
        
    }//GEN-LAST:event_jMenuItem_ClienteActionPerformed

    private void jMenuItem_ProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ProprietarioActionPerformed
        // Abrir parte do Proprietário
        
    }//GEN-LAST:event_jMenuItem_ProprietarioActionPerformed

    private void jMenuItem_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MarcaActionPerformed
        // Abrir parte da Marca
        
    }//GEN-LAST:event_jMenuItem_MarcaActionPerformed

    private void jMenuItem_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ModeloActionPerformed
        // Abrir parte do Modelo
        
    }//GEN-LAST:event_jMenuItem_ModeloActionPerformed

    private void jMenuItem_AcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AcessorioActionPerformed
        // Abrir parte do Acessório
        
    }//GEN-LAST:event_jMenuItem_AcessorioActionPerformed

    private void jMenuItem_VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_VeiculoActionPerformed
        // Abrir parte do Veículo
        
    }//GEN-LAST:event_jMenuItem_VeiculoActionPerformed

    private void jMenuItem_VeiculoAcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_VeiculoAcessorioActionPerformed
        // Abrir parte dos Acessíos do Veículo(tabela VeiculoAcessorio)
        
    }//GEN-LAST:event_jMenuItem_VeiculoAcessorioActionPerformed

    private void jMenuItem_OrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_OrdemDeServicoActionPerformed
        // Abrir parte da Ordem de Serviço
        
    }//GEN-LAST:event_jMenuItem_OrdemDeServicoActionPerformed

    private void jMenuItem_PecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PecaActionPerformed
        // Abrir parte da Peça
        
    }//GEN-LAST:event_jMenuItem_PecaActionPerformed

    private void jMenuItem_ItensDePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ItensDePecaActionPerformed
        // Abrir parte dos Itens de Peça
        
    }//GEN-LAST:event_jMenuItem_ItensDePecaActionPerformed

    private void jMenuItem_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ServicoActionPerformed
        // Abrir parte do Serviço
        
    }//GEN-LAST:event_jMenuItem_ServicoActionPerformed

    private void jMenuItem_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FuncionarioActionPerformed
        // Abrir parte do Funcionário
        
    }//GEN-LAST:event_jMenuItem_FuncionarioActionPerformed

    private void jMenuItem_ItensDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ItensDeServicoActionPerformed
        // Abrir parte dos Itens de Serviço
        
    }//GEN-LAST:event_jMenuItem_ItensDeServicoActionPerformed

  /**
   * @param args the command line arguments
   */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
              javax.swing.UIManager.setLookAndFeel(info.getClassName());
              break;
            }
          }
        } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane_InputDeTela;
    private javax.swing.JMenuBar jMenuBar_Opcoes;
    private javax.swing.JMenuItem jMenuItem_Acessorio;
    private javax.swing.JMenuItem jMenuItem_Cliente;
    private javax.swing.JMenuItem jMenuItem_Funcionario;
    private javax.swing.JMenuItem jMenuItem_ItensDePeca;
    private javax.swing.JMenuItem jMenuItem_ItensDeServico;
    private javax.swing.JMenuItem jMenuItem_Marca;
    private javax.swing.JMenuItem jMenuItem_Modelo;
    private javax.swing.JMenuItem jMenuItem_OrdemDeServico;
    private javax.swing.JMenuItem jMenuItem_Peca;
    private javax.swing.JMenuItem jMenuItem_Proprietario;
    private javax.swing.JMenuItem jMenuItem_Servico;
    private javax.swing.JMenuItem jMenuItem_Veiculo;
    private javax.swing.JMenuItem jMenuItem_VeiculoAcessorio;
    private javax.swing.JMenu jMenu_ClientesVeiculos;
    private javax.swing.JMenu jMenu_Oficina;
    private javax.swing.JMenu jMenu_OpcoesPeca;
    private javax.swing.JMenu jMenu_OpcoesServico;
    private javax.swing.JMenu jMenu_OpcoesVeiculo;
    private javax.swing.JMenu jMenu_PecasServicos;
    // End of variables declaration//GEN-END:variables
}
