/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.ICrud;
import modelos.Servicos;
import persistencia.ServicoDAO;

/**
 *
 * @author Cliente
 */
public class TelaCadastroServicos extends javax.swing.JInternalFrame {
 private ICrud<Servicos> servicoBD = null;
    /**
     * Creates new form TelaCadastroServicos
     */
    public TelaCadastroServicos() {
        initComponents();
    try {
      servicoBD = new ServicoDAO();
      mostrarServicosNaGrid();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
    }
    }
  private void limparTela(){
    jTextField1_IdServico.setText("");
    jTextField1_Descricao.setText("");
    jTextField1_Preco.setText("");
  }
  private void mostrarServicosNaGrid(){
  try {
    List<Servicos> listaDeServicos = new ArrayList<>();
    listaDeServicos = null;
    listaDeServicos = servicoBD.listar();
    if(listaDeServicos != null){
    DefaultTableModel model =  (DefaultTableModel) jTable_Servico.getModel();
    model.setNumRows(0); 
    if(listaDeServicos.isEmpty()) 
      throw new Exception("Lista de Servico BD Vazia");
 
    for(int pos = 0; pos < listaDeServicos.size(); pos++){
      Servicos objServico = listaDeServicos.get(pos);
      String[] saida = new String[3];
        saida[0] = objServico.getIdServico()+ "";
        saida[1] = objServico.getDescricaoServico()+ "";
        saida[2] = objServico.getPrecoServico()+ "";
      model.addRow(saida);
    }  
    }
  } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_IdServico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_Descricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_Preco = new javax.swing.JTextField();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Servico = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1146, 573));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE SERVICOS");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setText("IdServico");

        jTextField1_IdServico.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextField1_IdServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_IdServicoActionPerformed(evt);
            }
        });
        jTextField1_IdServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_IdServicoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setText("Descricao");

        jTextField1_Descricao.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextField1_Descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_DescricaoActionPerformed(evt);
            }
        });
        jTextField1_Descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_DescricaoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setText("Preco");

        jTextField1_Preco.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextField1_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_PrecoActionPerformed(evt);
            }
        });
        jTextField1_Preco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_PrecoKeyReleased(evt);
            }
        });

        jButton_Incluir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Incluir.setText("INCLUIR");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Alterar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Alterar.setText("ALTERAR");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton_Buscar.setText("BUSCAR");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jTable_Servico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IDServico", "Descricao", "Preco"
            }
        ));
        jTable_Servico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ServicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Servico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton_Incluir))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_Alterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Buscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1_IdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1_IdServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir)
                    .addComponent(jButton_Alterar)
                    .addComponent(jButton_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_IdServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_IdServicoActionPerformed

    }//GEN-LAST:event_jTextField1_IdServicoActionPerformed

    private void jTextField1_IdServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_IdServicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_IdServicoKeyReleased

    private void jTextField1_DescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_DescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_DescricaoActionPerformed

    private void jTextField1_DescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_DescricaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_DescricaoKeyReleased

    private void jTextField1_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_PrecoActionPerformed

    private void jTextField1_PrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_PrecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_PrecoKeyReleased

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
        if(jTextField1_IdServico.getText().isEmpty()) throw new Exception("Id vazio");
            Servicos objServico = new Servicos(Integer.parseInt(jTextField1_IdServico.getText()));
            objServico = (servicoBD.consultar(objServico));
            String aux = objServico.getPrecoServico();
            aux = aux.replace("R$", "").trim();
            
            jTextField1_IdServico.setText(objServico.getIdServico()+"");
            jTextField1_Descricao.setText(objServico.getDescricaoServico());
            jTextField1_Preco.setText(aux);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Buscar Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        try {
            String descricao = jTextField1_Descricao.getText().toUpperCase();
            if (descricao.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de descrição não pode estar vazio.");
            }
            
            // Verifica se o preço está vazio
            String precoTexto = jTextField1_Preco.getText().trim();
            precoTexto = precoTexto.replace(",", ".");
            if (precoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de preço não pode estar vazio.");
            }

            // Valida o preço com uma expressão regular
            if (!precoTexto.matches("\\d+(\\.\\d{1,2})?")) {
                JOptionPane.showMessageDialog(rootPane, "O preço deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45).");
            }
            System.out.println(precoTexto);
            Servicos objServico = new Servicos(0, descricao, precoTexto);
            servicoBD.incluir(objServico);
            limparTela();
            mostrarServicosNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        // TODO add your handling code here:
        try {
            String descricao = jTextField1_Descricao.getText().toUpperCase();
            if (descricao.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de descrição não pode estar vazio.");
            }
                    // Verifica se o preço está vazio
            String precoTexto = jTextField1_Preco.getText().trim();
            precoTexto = precoTexto.replace(",", ".");
            if (precoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de preço não pode estar vazio.");
            }

            // Valida o preço com uma expressão regular
            if (!precoTexto.matches("\\d+(\\.\\d{1,2})?")) {
                JOptionPane.showMessageDialog(rootPane, "O preço deve ser um número inteiro ou decimal com até duas casas decimais (ex.: 123 ou 123.45).");
            }
            Servicos objServico = new Servicos(Integer.parseInt(jTextField1_IdServico.getText()), descricao, precoTexto);
            servicoBD.alterar(objServico);
            limparTela();
            mostrarServicosNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Alterar Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jTable_ServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ServicoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable_Servico.getModel();
        int selectedRowIndex = jTable_Servico.getSelectedRow();
        
        jTextField1_IdServico.setText((String) model.getValueAt(selectedRowIndex, 0));
        jTextField1_Descricao.setText((String) model.getValueAt(selectedRowIndex, 1));
        
        String aux = (String) model.getValueAt(selectedRowIndex, 2);
        aux = aux.replace("R$", "").trim();
        jTextField1_Preco.setText(aux);
    }//GEN-LAST:event_jTable_ServicoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Servico;
    private javax.swing.JTextField jTextField1_Descricao;
    private javax.swing.JTextField jTextField1_IdServico;
    private javax.swing.JTextField jTextField1_Preco;
    // End of variables declaration//GEN-END:variables
}
