/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Endereco;
import modelos.ICrud;
import modelos.Telefone;
import modelos.enums.TipoClienteEnum;
import persistencia.ClienteDAO;

/**
 *
 * @author misuka
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    
    private ICrud<Cliente> clienteDB;
    
    private void carregarValoresDaComboBox(){
        for(TipoClienteEnum tipo : TipoClienteEnum.values()){
            jComboBox_Opcoes.addItem(tipo.getDescricao());
        }
    }
    
    public TelaCliente() {
        initComponents();
        try {
            clienteDB = new ClienteDAO();
            mostrarNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro: "+erro.getMessage());
        }
        carregarValoresDaComboBox();
        escolherEntrePessoaFisicaOuJuridica();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Opcoes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField_IdCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField_Telefone1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField_Telefone2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Logradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Bairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_CEP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Cidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jTextField_Estado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Complemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_CPF = new javax.swing.JTextField();
        jTextField_CNPJ = new javax.swing.JTextField();
        jTextField_Contato = new javax.swing.JTextField();
        jTextField_InscricaoEstadual = new javax.swing.JTextField();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Tipo de Pessoa");

        jComboBox_Opcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OpcoesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Telefone 1");

        try {
            jFormattedTextField_Telefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Telefone 2");

        try {
            jFormattedTextField_Telefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setText("Email");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setText("Logradouro");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setText("Número");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setText("Bairro");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setText("CEP");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setText("Cidade");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel12.setText("Estado");

        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone 1", "Telefone 2", "Email", "Endereço", "CPF", "CNPJ", "Contato", "Ins. Estad"
            }
        ));
        jTable_Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Saida);
        if (jTable_Saida.getColumnModel().getColumnCount() > 0) {
            jTable_Saida.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Saida.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable_Saida.getColumnModel().getColumn(5).setMinWidth(250);
            jTable_Saida.getColumnModel().getColumn(5).setPreferredWidth(250);
            jTable_Saida.getColumnModel().getColumn(5).setMaxWidth(250);
            jTable_Saida.getColumnModel().getColumn(6).setPreferredWidth(60);
            jTable_Saida.getColumnModel().getColumn(6).setMaxWidth(60);
            jTable_Saida.getColumnModel().getColumn(7).setMinWidth(60);
            jTable_Saida.getColumnModel().getColumn(7).setPreferredWidth(60);
            jTable_Saida.getColumnModel().getColumn(7).setMaxWidth(60);
            jTable_Saida.getColumnModel().getColumn(8).setMinWidth(60);
            jTable_Saida.getColumnModel().getColumn(9).setMinWidth(60);
        }

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setText("Complemento");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setText("CPF");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel15.setText("CNPJ");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel16.setText("Contato");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setText("Inscrição Estadual");

        jButton_Incluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton_Incluir.setText("Incluir");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Alterar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton_Alterar.setText("Alterar");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_InscricaoEstadual)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Bairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Logradouro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextField_Telefone2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_Cidade))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Contato))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CPF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton_Buscar)
                                    .addComponent(jButton_Alterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Incluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField_Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Incluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextField_Telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Alterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_InscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_OpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OpcoesActionPerformed
        // TODO add your handling code here:
        escolherEntrePessoaFisicaOuJuridica();
    }//GEN-LAST:event_jComboBox_OpcoesActionPerformed

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTextField_Nome.getText();
            if(nome.isEmpty()) throw new Exception("Nome Vazio");
            String email = jTextField_Email.getText();
            if(email.isEmpty()) throw new Exception("Email Vazio");
            
            String numeroTele1 = jFormattedTextField_Telefone1.getText();
            if(numeroTele1.equals("+  (  )         ")) throw new Exception("Telefone 1 Vazio");
            String[] telefonePartes = numeroTele1.split("[()]+");
            int ddi1 = Integer.parseInt(telefonePartes[0].substring(1));
            int ddd1 = Integer.parseInt(telefonePartes[1]);
            int numero1 = Integer.parseInt(telefonePartes[2]);
            Telefone telefone1 = new Telefone(ddi1,ddd1,numero1);
            
            
            Telefone telefone2 = null;
            String numeroTele2 = jFormattedTextField_Telefone2.getText();
            if(!numeroTele2.equals("+  (  )         ")){
                String[] telefonePartes2 = numeroTele2.split("[()]+");
                int ddi2 = Integer.parseInt(telefonePartes2[0].substring(1));
                int ddd2 = Integer.parseInt(telefonePartes2[1]);
                int numero2 = Integer.parseInt(telefonePartes2[2]);
                telefone2 = new Telefone(ddi2,ddd2,numero2);
            }
            
            if(jTextField_Logradouro.getText().isEmpty()) throw new Exception("Logradouro vazio");
            if(jTextField_Numero.getText().isEmpty()) throw new Exception("Nomero vazio");
            if(jTextField_CEP.getText().isEmpty()) throw new Exception("CEP vazio");
            if(jTextField_Bairro.getText().isEmpty()) throw new Exception("Bairro vazio");
            if(jTextField_Complemento.getText().isEmpty()) throw new Exception("Complemento vazio");
            if(jTextField_Cidade.getText().isEmpty()) throw new Exception("Cidade Vazia");
            if(jTextField_Estado.getText().isEmpty()) throw new Exception("Estado vazio");
            
            Endereco endereco = new Endereco(jTextField_Logradouro.getText().toUpperCase(), 
                    Integer.parseInt(jTextField_Numero.getText()), jTextField_CEP.getText(), 
                    jTextField_Bairro.getText().toUpperCase(),jTextField_Complemento.getText().toUpperCase(), 
                    jTextField_Cidade.getText().toUpperCase(),jTextField_Estado.getText().toUpperCase());
            
            Cliente objeto = new Cliente(0, nome, telefone1, telefone2, email, endereco, 
                    jComboBox_Opcoes.getSelectedItem().toString(), jTextField_CPF.getText(), 
                    jTextField_CNPJ.getText(), jTextField_Contato.getText(), 
                    jTextField_InscricaoEstadual.getText());
            
            clienteDB.incluir(objeto);
            limparDados();
            mostrarNaGrid();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Incluir: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        // TODO add your handling code here:
        try {
            if(jTextField_IdCliente.getText().isEmpty()) throw new Exception("Id vazio");
            int idCliente = Integer.parseInt(jTextField_IdCliente.getText());
            String nome = jTextField_Nome.getText();
            if(nome.isEmpty()) throw new Exception("Nome Vazio");
            String email = jTextField_Email.getText();
            if(email.isEmpty()) throw new Exception("Email Vazio");
            
            String numeroTele1 = jFormattedTextField_Telefone1.getText();
            if(numeroTele1.equals("+  (  )         ")) throw new Exception("Telefone 1 Vazio");
            String[] telefonePartes = numeroTele1.split("[()]+");
            int ddi1 = Integer.parseInt(telefonePartes[0].substring(1));
            int ddd1 = Integer.parseInt(telefonePartes[1]);
            int numero1 = Integer.parseInt(telefonePartes[2]);
            Telefone telefone1 = new Telefone(ddi1,ddd1,numero1);
            
            
            Telefone telefone2 = null;
            String numeroTele2 = jFormattedTextField_Telefone2.getText();
            if(!numeroTele2.equals("+  (  )         ")){
                String[] telefonePartes2 = numeroTele2.split("[()]+");
                int ddi2 = Integer.parseInt(telefonePartes2[0].substring(1));
                int ddd2 = Integer.parseInt(telefonePartes2[1]);
                int numero2 = Integer.parseInt(telefonePartes2[2]);
                telefone2 = new Telefone(ddi2,ddd2,numero2);
            }
            
            if(jTextField_Logradouro.getText().isEmpty()) throw new Exception("Logradouro vazio");
            if(jTextField_Numero.getText().isEmpty()) throw new Exception("Nomero vazio");
            if(jTextField_CEP.getText().isEmpty()) throw new Exception("CEP vazio");
            if(jTextField_Bairro.getText().isEmpty()) throw new Exception("Bairro vazio");
            if(jTextField_Complemento.getText().isEmpty()) throw new Exception("Complemento vazio");
            if(jTextField_Cidade.getText().isEmpty()) throw new Exception("Cidade Vazia");
            if(jTextField_Estado.getText().isEmpty()) throw new Exception("Estado vazio");
            
            Endereco endereco = new Endereco(jTextField_Logradouro.getText().toUpperCase(), 
                    Integer.parseInt(jTextField_Numero.getText()), jTextField_CEP.getText(), 
                    jTextField_Bairro.getText().toUpperCase(),jTextField_Complemento.getText().toUpperCase(), 
                    jTextField_Cidade.getText().toUpperCase(),jTextField_Estado.getText().toUpperCase());
            
            Cliente objeto = new Cliente(idCliente, nome, telefone1, telefone2, email, endereco, 
                    jComboBox_Opcoes.getSelectedItem().toString(), jTextField_CPF.getText(), 
                    jTextField_CNPJ.getText(), jTextField_Contato.getText(), 
                    jTextField_InscricaoEstadual.getText());
            
            clienteDB.alterar(objeto);
            limparDados();
            mostrarNaGrid();
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            
            if(jTextField_IdCliente.getText().isEmpty()) throw new Exception("Id vazio");
            int idCliente = Integer.parseInt(jTextField_IdCliente.getText());
            Cliente objeto = new Cliente(idCliente);
            objeto = clienteDB.consultar(objeto);
            
            jComboBox_Opcoes.setSelectedItem(objeto.getTipoCliente());
            escolherEntrePessoaFisicaOuJuridica();
            jTextField_Nome.setText(objeto.getNome());
            jTextField_Email.setText(objeto.getEmail());
            jTextField_CEP.setText(objeto.getEndereco().getCep());
            jTextField_CNPJ.setText(objeto.getCnpj());
            jTextField_Contato.setText(objeto.getContato());
            jTextField_InscricaoEstadual.setText(objeto.getInscricaoEstadual());
            jTextField_CPF.setText(objeto.getCpf());
            jTextField_Logradouro.setText(objeto.getEndereco().getLogradouro());
            jTextField_Numero.setText(objeto.getEndereco().getNumeroEndereco()+"");
            jTextField_Bairro.setText(objeto.getEndereco().getBairro());
            jTextField_Cidade.setText(objeto.getEndereco().getCidade());
            jTextField_Estado.setText(objeto.getEndereco().getEstado());
            jTextField_Complemento.setText(objeto.getEndereco().getComplemento());
            String valueTelefone1 = ""+objeto.getTelefone1().getDdi()+objeto.getTelefone1().getDdd()+objeto.getTelefone1().getNumero();
            System.out.println(valueTelefone1);
            jFormattedTextField_Telefone1.setText(valueTelefone1);
            if(objeto.getTelefone2() != null){
                String valueTelefone2 = ""+objeto.getTelefone2().getDdi()+objeto.getTelefone2().getDdd()+objeto.getTelefone2().getNumero();
                jFormattedTextField_Telefone1.setText(valueTelefone2);
            }else{
                jFormattedTextField_Telefone2.setValue(null);
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Buscar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTable_SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SaidaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable_Saida.getModel();
        int selectedRowIndex = jTable_Saida.getSelectedRow();
        
        jTextField_IdCliente.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField_Nome.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jFormattedTextField_Telefone1.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jFormattedTextField_Telefone2.setText(model.getValueAt(selectedRowIndex, 3).toString());
        jTextField_Email.setText(model.getValueAt(selectedRowIndex, 4).toString());
        
        String auxEnd = model.getValueAt(selectedRowIndex, 5).toString();
        String vetEnd[] = auxEnd.split("[;-]");
        jTextField_Logradouro.setText(vetEnd[0]);
        jTextField_Numero.setText(vetEnd[1]);
        jTextField_Complemento.setText(vetEnd[2]);
        jTextField_Bairro.setText(vetEnd[3]);
        jTextField_Cidade.setText(vetEnd[4]);
        jTextField_Estado.setText(vetEnd[5]);
        jTextField_CEP.setText(vetEnd[6]);
        
        if(model.getValueAt(selectedRowIndex, 6).toString().compareTo("") == 0){
            jComboBox_Opcoes.setSelectedItem("Pessoa Jurídica");
            escolherEntrePessoaFisicaOuJuridica();
            jTextField_CNPJ.setText(model.getValueAt(selectedRowIndex, 7).toString());
            jTextField_Contato.setText(model.getValueAt(selectedRowIndex, 8).toString());
            jTextField_InscricaoEstadual.setText(model.getValueAt(selectedRowIndex, 9).toString());
        } else {
            jComboBox_Opcoes.setSelectedItem("Pessoa Física");
            escolherEntrePessoaFisicaOuJuridica();
            jTextField_CPF.setText(model.getValueAt(selectedRowIndex, 6).toString());
        }
    }//GEN-LAST:event_jTable_SaidaMouseClicked
    
    private void escolherEntrePessoaFisicaOuJuridica(){
        String selecionado = jComboBox_Opcoes.getSelectedItem().toString();
        if(selecionado.equals("Pessoa Física")){
            jTextField_CPF.setEnabled(true);
            jTextField_CNPJ.setEnabled(false);
            jTextField_Contato.setEnabled(false);
            jTextField_InscricaoEstadual.setEnabled(false);
        }
        else if(selecionado.equals("Pessoa Jurídica")){
            jTextField_CPF.setEnabled(false);
            jTextField_CNPJ.setEnabled(true);
            jTextField_Contato.setEnabled(true);
            jTextField_InscricaoEstadual.setEnabled(true);
        }
    }
    
    private void mostrarNaGrid(){
        try {
            List<Cliente> listaDeClientes = null;
            listaDeClientes = clienteDB.listar();
            DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
            model.setNumRows(0); 
            if(listaDeClientes.isEmpty()) throw new Exception("Lista de Oficina BD Vazia");

            jTable_Saida.setRowHeight(75);
            for(int j = 0; j<10;j++){
                jTable_Saida.getColumnModel().getColumn(j).setCellRenderer(new MultiLineTableCellRenderer());
            }
            for(int pos = 0; pos < listaDeClientes.size(); pos++){
                Cliente objCliente = listaDeClientes.get(pos);
                String[] saida = new String[10];
                    saida[0] = objCliente.getIdCliente()+"";
                    saida[1] = objCliente.getNome();
                    saida[2] = objCliente.getTelefone1().toString();
                    if(objCliente.getTelefone2() != null){
                        saida[3] = objCliente.getTelefone2().toString();
                    }
                    else{
                        saida[3] = "";
                    }
                    saida[4] = objCliente.getEmail();
                    saida[5] = objCliente.getEndereco().toString();
                    saida[6] = objCliente.getCpf();
                    saida[7] = objCliente.getCnpj();
                    saida[8] = objCliente.getContato();
                    saida[9] = objCliente.getContato();
                    saida[9] = objCliente.getInscricaoEstadual();
                model.addRow(saida);
            }  
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
          }    
    }
    
    private void limparDados(){
        jTextField_IdCliente.setText("");
        jTextField_Nome.setText("");
        jTextField_Email.setText("");
        jTextField_CEP.setText("");
        jTextField_CNPJ.setText("");
        jTextField_Contato.setText("");
        jTextField_InscricaoEstadual.setText("");
        jTextField_CPF.setText("");
        jTextField_Logradouro.setText("");
        jTextField_Numero.setText("");
        jTextField_Bairro.setText("");
        jTextField_Cidade.setText("");
        jTextField_Estado.setText("");
        jTextField_Complemento.setText("");
        jFormattedTextField_Telefone1.setValue(null);
        jFormattedTextField_Telefone2.setValue(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JComboBox<String> jComboBox_Opcoes;
    private javax.swing.JFormattedTextField jFormattedTextField_Telefone1;
    private javax.swing.JFormattedTextField jFormattedTextField_Telefone2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    private javax.swing.JTextField jTextField_Bairro;
    private javax.swing.JTextField jTextField_CEP;
    private javax.swing.JTextField jTextField_CNPJ;
    private javax.swing.JTextField jTextField_CPF;
    private javax.swing.JTextField jTextField_Cidade;
    private javax.swing.JTextField jTextField_Complemento;
    private javax.swing.JTextField jTextField_Contato;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Estado;
    private javax.swing.JTextField jTextField_IdCliente;
    private javax.swing.JTextField jTextField_InscricaoEstadual;
    private javax.swing.JTextField jTextField_Logradouro;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_Numero;
    // End of variables declaration//GEN-END:variables
}
