/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Acessorio;
import modelos.ICrud;
import modelos.Veiculo;
import modelos.VeiculoAcessorio;
import persistencia.AcessorioDAO;
import persistencia.VeiculoAcessorioDAO;
import persistencia.VeiculoDAO;

/**
 *
 * @author Cliente
 */
public class TelaVeiculoAcessorio extends javax.swing.JInternalFrame {
    private ICrud<Acessorio> AcessorioBD = null;
    private ICrud<Veiculo> VeiculoBD = null;
    private ICrud<VeiculoAcessorio> VeiculoAcessorioBD = null;
    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculoAcessorio() {
        initComponents();
        try {
            AcessorioBD = new AcessorioDAO();
            VeiculoBD = new VeiculoDAO();
            VeiculoAcessorioBD = new VeiculoAcessorioDAO();
            List<Acessorio> listaDeAcessorios = new ArrayList<>();
            listaDeAcessorios = null;
            listaDeAcessorios = AcessorioBD.listar();
            jComboBox_acessorio.removeAllItems();
            for(int pos = 0; pos < listaDeAcessorios.size(); pos++){
              jComboBox_acessorio.addItem(listaDeAcessorios.get(pos).toString());
            }
            List<Veiculo> listaDeVeiculos = new ArrayList<>();
            listaDeVeiculos = null;
            listaDeVeiculos = VeiculoBD.listar();
            jComboBox_placa.removeAllItems();
            for(int pos = 0; pos < listaDeVeiculos.size(); pos++){
              jComboBox_placa.addItem(listaDeVeiculos.get(pos).toString());
            }
          mostrarVeiculoAcessorioNaGrid();
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
        }
    }
    
    private void mostrarVeiculoAcessorioNaGrid(){
    try {
      List<VeiculoAcessorio> listaDeVeiculoAcessorio = new ArrayList<>();
      listaDeVeiculoAcessorio = null;
      listaDeVeiculoAcessorio = VeiculoAcessorioBD.listar();
      DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
      model.setNumRows(0); 
      if(listaDeVeiculoAcessorio.isEmpty()) 
        throw new Exception("Lista de Acessorio BD Vazia");
      for(int j = 0; j<2;j++){
          jTable_Saida.getColumnModel().getColumn(j);
           }
      for(int pos = 0; pos < listaDeVeiculoAcessorio.size(); pos++){
        VeiculoAcessorio objVeiculoAcessorio = listaDeVeiculoAcessorio.get(pos);
        String[] saida = new String[2];
          saida[0] = VeiculoBD.consultar(objVeiculoAcessorio.getVeiculo()).toString()+ "";
          saida[1] = AcessorioBD.consultar(objVeiculoAcessorio.getAcessorio()).toString()+ "";
        model.addRow(saida);
      }  
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro.getMessage());
      }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jButtonincluir = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_acessorio = new javax.swing.JComboBox<>();
        jComboBox_placa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1119, 466));

        jTable_Saida.setBackground(new java.awt.Color(153, 255, 204));
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Veiculo", "Acessorio"
            }
        ));
        jTable_Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Saida);

        jButtonincluir.setBackground(new java.awt.Color(0, 153, 0));
        jButtonincluir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButtonincluir.setForeground(new java.awt.Color(0, 255, 204));
        jButtonincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/seta.png"))); // NOI18N
        jButtonincluir.setText("INCLUIR");
        jButtonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonincluirActionPerformed(evt);
            }
        });

        jButton_alterar.setBackground(new java.awt.Color(0, 153, 0));
        jButton_alterar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton_alterar.setForeground(new java.awt.Color(0, 255, 204));
        jButton_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/troca.png"))); // NOI18N
        jButton_alterar.setText("ALTERAR");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });

        jButton_buscar.setBackground(new java.awt.Color(0, 153, 0));
        jButton_buscar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(0, 255, 204));
        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/procurar.png"))); // NOI18N
        jButton_buscar.setText("BUSCAR");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Acessorio");

        jComboBox_acessorio.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox_acessorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jComboBox_placa.setBackground(new java.awt.Color(204, 255, 204));
        jComboBox_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Placa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonincluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_alterar)
                                .addGap(111, 111, 111)
                                .addComponent(jButton_buscar))
                            .addComponent(jComboBox_placa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_acessorio, 0, 539, Short.MAX_VALUE))
                        .addGap(0, 447, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_acessorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonincluir)
                    .addComponent(jButton_alterar)
                    .addComponent(jButton_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonincluirActionPerformed
        // TODO add your handling code here:
        try {
            String aux = (String)jComboBox_placa.getSelectedItem();
            //System.out.println(aux);
            String[] vetVeiculo = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            String placa = vetVeiculo[0];
            Veiculo veiculo = new Veiculo(placa);
            
            aux = (String)jComboBox_acessorio.getSelectedItem();
            String[] vetAcessorio = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            int idAcessorio = Integer.parseInt(vetAcessorio[0]);
            Acessorio acessorio = new Acessorio(idAcessorio);
            
            VeiculoAcessorio objVeiculoAcesssorio = new VeiculoAcessorio(veiculo,acessorio);
            VeiculoAcessorioBD.incluir(objVeiculoAcesssorio);
            mostrarVeiculoAcessorioNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButtonincluirActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
        // TODO add your handling code here:
        try {
            String aux = (String)jComboBox_placa.getSelectedItem();
            //System.out.println(aux);
            String[] vetVeiculo = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            String placa = vetVeiculo[0];
            Veiculo veiculo = new Veiculo(placa);
            
            aux = (String)jComboBox_acessorio.getSelectedItem();
            String[] vetAcessorio = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            int idAcessorio = Integer.parseInt(vetAcessorio[0]);
            Acessorio acessorio = new Acessorio(idAcessorio);
            
            VeiculoAcessorio objVeiculoAcesssorio = new VeiculoAcessorio(veiculo,acessorio);
            VeiculoAcessorioBD.alterar(objVeiculoAcesssorio);
            mostrarVeiculoAcessorioNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try {
            String aux = (String)jComboBox_placa.getSelectedItem();
            //System.out.println(aux);
            String[] vetVeiculo = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            String placa = vetVeiculo[0];
            Veiculo veiculo = new Veiculo(placa);
            
            aux = (String)jComboBox_acessorio.getSelectedItem();
            String[] vetAcessorio = aux.split("-");
            //System.out.println(vetAcessorio[0]);
            int idAcessorio = Integer.parseInt(vetAcessorio[0]);
            Acessorio acessorio = new Acessorio(idAcessorio);
            
            VeiculoAcessorio objVeiculoAcesssorioBusca = new VeiculoAcessorio(veiculo,acessorio);
            objVeiculoAcesssorioBusca = (VeiculoAcessorioBD.consultar(objVeiculoAcesssorioBusca));
            jComboBox_acessorio.setSelectedItem(VeiculoBD.consultar(objVeiculoAcesssorioBusca.getVeiculo()).toString());
            jComboBox_acessorio.setSelectedItem(AcessorioBD.consultar(objVeiculoAcesssorioBusca.getAcessorio()).toString());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Buscar: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTable_SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SaidaMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel)jTable_Saida.getModel();
            int selectedRowIndex = jTable_Saida.getSelectedRow();

            String auxVeiculo = (String) model.getValueAt(selectedRowIndex, 0);
            String vetVeiculo[] = auxVeiculo.split("-");
            Veiculo veiculo = new Veiculo(vetVeiculo[0]);
            jComboBox_placa.setSelectedItem(VeiculoBD.consultar(veiculo).toString());
            
            String auxAcessorio = (String) model.getValueAt(selectedRowIndex, 1);
            String vetAcessorio[] = auxAcessorio.split("-");
            Acessorio acessorio = new Acessorio(Integer.parseInt(vetAcessorio[0]));
            jComboBox_acessorio.setSelectedItem(AcessorioBD.consultar(acessorio).toString());
        } catch (Exception ex) {
            Logger.getLogger(TelaVeiculoAcessorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_SaidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButtonincluir;
    private javax.swing.JComboBox<String> jComboBox_acessorio;
    private javax.swing.JComboBox<String> jComboBox_placa;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    // End of variables declaration//GEN-END:variables
}
