/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.ICrud;
import modelos.Marca;
import modelos.Modelo;
import modelos.Veiculo;
import persistencia.ModeloDAO;
import persistencia.VeiculoDAO;

/**
 *
 * @author Cliente
 */
public class TelaVeiculo extends javax.swing.JInternalFrame {
    private ICrud<Modelo> ModeloBD = null;
    private ICrud<Veiculo> VeiculoBD = null;
    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
        try {
            ModeloBD = new ModeloDAO();
            VeiculoBD = new VeiculoDAO();
          
            List<Modelo> listaDeModelo = new ArrayList<>();
            listaDeModelo = null;
            listaDeModelo = ModeloBD.listar();
            jComboBox_Modelo.removeAllItems();
            for(int pos = 0; pos < listaDeModelo.size(); pos++){
              jComboBox_Modelo.addItem(listaDeModelo.get(pos).toString());
            }
          mostrarVeiculoNaGrid();
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
        }
    }
        private void limparTela(){
      jTextField_chassi.setText("");
      jTextField_kilometragem.setText("");
      jTextField_patrimonio.setText("");
      jTextField_placa.setText("");
      jFormattedTextField_anoFabricacao.setValue(null);
      jFormattedTextField_anoModelo.setValue(null);
      jFormattedTextField_dataRegistro.setValue(null);
    }
    
    private void mostrarVeiculoNaGrid(){
    try {
      List<Veiculo> listaDeVeiculo = new ArrayList<>();
      listaDeVeiculo = null;
      listaDeVeiculo = VeiculoBD.listar();
      DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
      model.setNumRows(0); 
      if(listaDeVeiculo.isEmpty()) 
        throw new Exception("Lista de Acessorio BD Vazia");
      for(int j = 0; j<3;j++){
          jTable_Saida.getColumnModel().getColumn(j);
           }
      for(int pos = 0; pos < listaDeVeiculo.size(); pos++){
        Veiculo objVeiculo = listaDeVeiculo.get(pos);
        String[] saida = new String[8];
          saida[0] = objVeiculo.getPlaca()+ "";
          saida[1] = objVeiculo.getAnoFabricacao()+ "";
          saida[2] = objVeiculo.getDataRegistro()+ "";
          saida[3] = objVeiculo.getChassi()+ "";
          saida[4] = objVeiculo.getPatrimanio()+ "";
          saida[5] = objVeiculo.getKilometragem()+ "";
          saida[6] = objVeiculo.getAnoModelo()+ "";
          saida[7] = objVeiculo.getModelo().getIdModelo()+ "";
        model.addRow(saida);
      }  
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro.getMessage());
      }    
    }
    
    private void mostrarVeiculoNaGridBusca(Veiculo objVeiculo){
      try {

        DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
        model.setNumRows(0); 
        if(objVeiculo == null) 
          throw new Exception("Lista de Busca BD Vazia");
        for(int j = 0; j<3;j++){
            jTable_Saida.getColumnModel().getColumn(j);
             }
          String[] saida = new String[8];
          saida[0] = objVeiculo.getPlaca()+ "";
          saida[1] = objVeiculo.getAnoFabricacao()+ "";
          saida[2] = objVeiculo.getDataRegistro()+ "";
          saida[3] = objVeiculo.getChassi()+ "";
          saida[4] = objVeiculo.getPatrimanio()+ "";
          saida[5] = objVeiculo.getKilometragem()+ "";
          saida[6] = objVeiculo.getAnoModelo()+ "";
          saida[7] = objVeiculo.getModelo().getIdModelo()+ "";
          model.addRow(saida);
      } catch (Exception erro) {
          JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jButtonincluir = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jButton_listar = new javax.swing.JButton();
        jTextField_patrimonio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_kilometragem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_placa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField_anoFabricacao = new javax.swing.JFormattedTextField();
        jTextField_chassi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField_dataRegistro = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField_anoModelo = new javax.swing.JFormattedTextField();
        jComboBox_Modelo = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1119, 466));

        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "placa", "anoFabricacao", "dataRegistro", "chassi", "patrimonio", "kilometragem", "anoModelo", "idModelo"
            }
        ));
        jScrollPane1.setViewportView(jTable_Saida);

        jButtonincluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonincluir.setText("INCLUIR");
        jButtonincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonincluirActionPerformed(evt);
            }
        });

        jButton_alterar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_alterar.setText("ALTERAR");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });

        jButton_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_buscar.setText("BUSCAR");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jButton_listar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_listar.setText("LISTAR");
        jButton_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listarActionPerformed(evt);
            }
        });

        jTextField_patrimonio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("kilometragem");

        jTextField_kilometragem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("PLACA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("modelo");

        jTextField_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setText("anoFabricacao");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("chassi");

        try {
            jFormattedTextField_anoFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextField_chassi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setText("dataRegistro");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("patrimonio");

        try {
            jFormattedTextField_dataRegistro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel11.setText("anoModelo");

        try {
            jFormattedTextField_anoModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBox_Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextField_anoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextField_dataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_patrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_kilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextField_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonincluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_alterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_listar)))
                        .addGap(0, 266, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jFormattedTextField_anoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jTextField_patrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jFormattedTextField_dataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_kilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jFormattedTextField_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonincluir)
                    .addComponent(jButton_alterar)
                    .addComponent(jButton_buscar)
                    .addComponent(jButton_listar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonincluirActionPerformed
        // TODO add your handling code here:
        try {
            String aux = (String)jComboBox_Modelo.getSelectedItem();
            //System.out.println(aux);
            String[] vetModelo = aux.split("-");
            //System.out.println(vetModelo[0]);
            int idModelo = Integer.parseInt(vetModelo[0]);
            Modelo modelo = new Modelo(idModelo);
            
            String anoFabricacaoTexto = jFormattedTextField_anoFabricacao.getText().trim();
            // Verifica se o campo de data está vazio
            if (anoFabricacaoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            String dataRegistroTexto = jFormattedTextField_dataRegistro.getText().trim();
            // Verifica se o campo de data está vazio
            if (dataRegistroTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            String anoModeloTexto = jFormattedTextField_anoModelo.getText().trim();
            // Verifica se o campo de data está vazio
            if (anoModeloTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            // Define o formato esperado (dia/mês/ano)
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            formato.setLenient(false); // Garante validação estrita da data
            // Converte o texto para um objeto Date
            Date anoFabricacao = formato.parse(anoFabricacaoTexto);
            Date dataRegistro = formato.parse(dataRegistroTexto);
            Date anoModelo = formato.parse(anoModeloTexto);

            Veiculo objVeiculo = new Veiculo(jTextField_placa.getText(), anoFabricacao, dataRegistro, jTextField_chassi.getText(),Integer.parseInt(jTextField_patrimonio.getText()),Integer.parseInt(jTextField_kilometragem.getText()), anoModelo, modelo);
            VeiculoBD.incluir(objVeiculo);
            limparTela();
            mostrarVeiculoNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButtonincluirActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
        // TODO add your handling code here:
        try {
            String aux = (String)jComboBox_Modelo.getSelectedItem();
            //System.out.println(aux);
            String[] vetModelo = aux.split("-");
            //System.out.println(vetModelo[0]);
            int idModelo = Integer.parseInt(vetModelo[0]);
            Modelo modelo = new Modelo(idModelo);
            
            String anoFabricacaoTexto = jFormattedTextField_anoFabricacao.getText().trim();
            // Verifica se o campo de data está vazio
            if (anoFabricacaoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            String dataRegistroTexto = jFormattedTextField_dataRegistro.getText().trim();
            // Verifica se o campo de data está vazio
            if (dataRegistroTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            String anoModeloTexto = jFormattedTextField_anoModelo.getText().trim();
            // Verifica se o campo de data está vazio
            if (anoModeloTexto.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O campo de data não pode estar vazio.");
                return; // Sai do método para evitar execução adicional
            }
            // Define o formato esperado (dia/mês/ano)
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            formato.setLenient(false); // Garante validação estrita da data
            // Converte o texto para um objeto Date
            Date anoFabricacao = formato.parse(anoFabricacaoTexto);
            Date dataRegistro = formato.parse(dataRegistroTexto);
            Date anoModelo = formato.parse(anoModeloTexto);
            Veiculo objVeiculo = new Veiculo(jTextField_placa.getText(), anoFabricacao, dataRegistro, jTextField_chassi.getText(),Integer.parseInt(jTextField_patrimonio.getText()),Integer.parseInt(jTextField_kilometragem.getText()), anoModelo, modelo);
            VeiculoBD.alterar(objVeiculo);
            limparTela();
            mostrarVeiculoNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try {
            Veiculo buscarVeiculo = new Veiculo(jTextField_placa.getText());
            mostrarVeiculoNaGridBusca(VeiculoBD.consultar(buscarVeiculo));
            limparTela();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listarActionPerformed
        // TODO add your handling code here:
        mostrarVeiculoNaGrid();
    }//GEN-LAST:event_jButton_listarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_listar;
    private javax.swing.JButton jButtonincluir;
    private javax.swing.JComboBox<String> jComboBox_Modelo;
    private javax.swing.JFormattedTextField jFormattedTextField_anoFabricacao;
    private javax.swing.JFormattedTextField jFormattedTextField_anoModelo;
    private javax.swing.JFormattedTextField jFormattedTextField_dataRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    private javax.swing.JTextField jTextField_chassi;
    private javax.swing.JTextField jTextField_kilometragem;
    private javax.swing.JTextField jTextField_patrimonio;
    private javax.swing.JTextField jTextField_placa;
    // End of variables declaration//GEN-END:variables
}
